- name: Install required utils
  apt: name={{ item }} state=present 
  become: yes
  with_items:
    - git
    - zip
    - gcc
    - make
 
    
- name: Git clone FFmpeg repo
  become: yes
  git: repo=https://github.com/FFmpeg/FFmpeg.git dest=/home/{{learner_user}}/ffmpeg version=release/3.0 
  ignore_errors: yes


- name: change the permissions of ffmpeg
  become: yes
  file: path=/home/{{learner_user}}/ffmpeg owner={{learner_user}} group={{learner_user}} recurse=yes


- name: run the command ./configure
  become: yes
  become_user: "{{learner_user}}"
  command: chdir=/home/{{learner_user}}/ffmpeg  ./configure --disable-yasm

       
- name: run the command make
  become: yes
  command: chdir=/home/{{learner_user}}/ffmpeg  make


- name: run the command make install
  become: yes
  command: chdir=/home/{{learner_user}}/ffmpeg make install

- name: move ffmpeg files
  become: yes
  command: cp {{ learner_user_home }}/ffmpeg/{{ item }} /usr/local/bin
  with_items:
             - ffmpeg
             - ffprobe
             - ffserver
  
- name: Change permissions after copying ffmpeg files
  become: yes
  file: path=/usr/local/bin/{{ item }} owner={{learner_user}} group={{learner_user}} mode=0755
  with_items:
     - ffmpeg
     - ffprobe
     - ffserver
