---
- include: deploy.yml
  when: deploy_jobs | default(false)
  
- include: deploy-aws.yml
  when: cloud_store == 'aws'

- include: stop_jobs.yml
  when: stop_jobs | default(false)

- include: start_jobs.yml
  when: start_jobs | default(false)
