learner_user: learning
learner_group: learning
learner_user_home: /home/{{learner_user}}

backup_add: "127.0.0.1:7362"
var1: "_graph"
service: learning
graph_machine: "{{service}}{{var1}}"

neo4j_backup_dir: "{{ learner_user_home }}/backup"

cloud_storage_neo4jbackup_bucketname: "{{ cloud_storage_management_bucketname }}"
cloud_storage_neo4jbackup_foldername: neo4j-backup

