---
- name: "Start Nodemanager on Slaves"
  hosts: "lp-yarn-slave"
  become: yes
  tasks:
    - name: Ensure yarn nodemanager is running
      become_user: hduser
      shell: |
         (ps aux | grep yarn-hduser-nodemanager | grep -v grep) || /usr/local/hadoop/sbin/yarn-daemon.sh --config /usr/local/hadoop-{{hadoop_version}}/conf/ start nodemanager || sleep 10

    - name: Install mysql client
      apt: name=mysql-client state=present

    - name: install imagemagick
      apt: name=imagemagick state=present update_cache=yes

- name: "Copy Samza jobs additional configuration to slaves"
  become: yes
  hosts: "lp-yarn-slave"
  roles:
    - samza-jobs-additional-config

- name: "Deploy Samza jobs"
  hosts: "lp-yarn-master"
  become: yes
  vars_files:
    - "{{ secrets_path }}"
  vars:
    deploy_jobs: true
  roles:
    - samza-jobs
