es_restore_host: localhost
snapshot_create_request_body: {
    type: azure,
    settings: {
      container: "elasticsearch-snapshots",
      base_path: "{{ snapshot_base_path }}"
    }
}
snapshot_base_path: folderNameInTheAzureContainer 
