neo4j_restore_dir: /home/{{learner_user}}/restore
learner_user: learning
neo4j_restore_gzip_file_name:
neo4j_restore_azure_storage_account_name:
neo4j_restore_azure_storage_access_key:
neo4j_restore_azure_container_name:
neo4j_home: "{{learner_user_home}}/{{neo4j_dir}}/neo4j-enterprise-3.3.0"
learner_user_home: /home/{{learner_user}}