- name: create topics
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{ingestion_zookeeper_ip}}:2181 --create --topic {{env}}.{{item.name}} --partitions {{ item.num_of_partitions }} --replication-factor {{ item.replication_factor }}
  with_items: "{{ingestion_kafka_topics}}"
  ignore_errors: true
  when: kafka_id=="1"
  tags:
    - ingestion-kafka

- name: override retention time
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{ingestion_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --config retention.ms={{ item.retention_time }}
  with_items: "{{ingestion_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.retention_time is defined
  tags:
    - ingestion-kafka

- name: override replication count
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{ingestion_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --replication-factor {{ item.replication_factor }}
  with_items: "{{ingestion_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.replication_factor is defined
  tags:
    - ingestion-kafka

- name: override partition count
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{ingestion_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --partitions {{ item.num_of_partitions }}
  with_items: "{{ingestion_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.num_of_partitions is defined
  tags:
    - ingestion-kafka

- name: create topics
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --create --topic {{env}}.{{item.name}} --partitions {{ item.num_of_partitions }} --replication-factor {{ item.replication_factor }}
  with_items: "{{processing_kafka_topics}}"
  ignore_errors: true
  when: kafka_id=="1" and processing_kafka_topics | length > 0
  tags:
    - processing-kafka

- name: override retention time
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --config retention.ms={{ item.retention_time }}
  with_items: "{{processing_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.retention_time is defined  
  tags:
    - processing-kafka


- name: override replication count
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --replication-factor {{ item.replication_factor }}
  with_items: "{{processing_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.replication_factor is defined
  tags:
    - processing-kafka

- name: override partition count
  command: /opt/kafka/bin/kafka-topics.sh --zookeeper {{processing_zookeeper_ip}}:2181 --alter --topic {{env}}.{{item.name}} --partitions {{ item.num_of_partitions }}
  with_items: "{{processing_kafka_overriden_topics}}"
  when: kafka_id=="1" and item.num_of_partitions is defined
  tags:
    - processing-kafka