version: 2.1
jobs:
  lp-build:
    machine:
      image: ubuntu-2004:202201-02
      java:
        version: oraclejdk8
    steps:
      - checkout
      - restore_cache:
          key: lp-dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: mvn clean install -DskipTests=true

      - save_cache:
          key: lp-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2

      - run:
          name: Copy artifacts to one location
          command: mkdir artifacts && cp platform-modules/service/target/learning-service.war artifacts/ && cp platform-tools/spikes/sync-tool/target/sync-tool-0.0.1-SNAPSHOT.jar artifacts/

      - store_artifacts:
         path: artifacts
         destination: artifacts/

      - run: 
          name: Setup VM, Test and Update Sonar
          command: bash vmsetup.sh
     
workflows:
  version: 2.1
  workflow:
    jobs:
      - lp-build
