version: 2.1
jobs:
  lp-build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: lp-dependency-cache-{{ checksum "pom.xml" }}
      - run: bash vmsetup.sh

      - save_cache:
          key: lp-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      
      - run: wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')
      - run: find . -name jacoco.xml | awk '{print "java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r " $0 " --partial"}' | bash
      - run: java -jar ~/codacy-coverage-reporter-assembly-latest.jar final
        
workflows:
  version: 2.1
  workflow:
    jobs:
      - lp-build
