learner_user: learning
learner_user_home: /home/{{learner_user}}

learning_neo4j_bolt_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
language_neo4j_bolt_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:8687
learning_read_elb_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
learning_write_elb_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:7687
language_read_elb_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:8687
language_write_elb_url: bolt://{{ groups['learning-neo4j-node1'][0] }}:8687
object_bookmark_expiry_in_seconds: 15
environment_id: 10000000
search_index_host: "{{ groups['composite-search-cluster'][0] }}:9200"
hierarchy_keyspace_name: "{{env}}_hierarchy_store"
content_keyspace_name: "{{env}}_content_store"
sunbirddev_dialcode_store: "{{env}}_dialcode_store"
youtube_app_name: fetch-youtube-license
instance: "{{env}}"
instance_name: 
compositesearch_index_name: "compositesearch"

lp_cassandra_connection: "{{groups['cassandra']|join(':9042,')}}:9042"
redis_port: 6379
graphevent_kafka_url: "{{groups['processing-cluster-zookeepers']|join(':9092,')}}:9092"
search_lms_index_host: "{{ groups['core-es']|join(':9200,')}}:9200"

cloud_store: cephs3
azure_public_container: 
azure_account_name: