learner_user: learning
learner_user_home: /home/{{learner_user}}
logstash_home: "{{learner_user_home}}/logstash-{{logstash_version}}"
graphevent_kafka_url: "{{groups['processing-cluster-zookeepers']|join(':9092,')}}:9092"
graphevent_kafka_topic_id: "{{env}}.learning.graph.events"
rawtelemetry_event_topic_id: "{{env}}.telemetry.raw"
logstash_version: 6.3.1
backend_event_topic_id: "{{env}}.telemetry.backend"
platform:
 logstash_config: ['logstash-lp']
