---
- name: Print the command to console
  debug:
    var: command

- name: Print the parameters to console
  debug:
    var: parameters

- name: Delete existing configuration files
  file: name="{{learner_user_home}}/sync_tool" state=absent

- name: Create directory
  file: name={{learner_user_home}}/sync_tool state=directory mode=755 owner="{{learner_user}}" group="{{learner_user}}"

- name: Copy application.conf file
  template: src=application.conf.j2 dest={{learner_user_home}}/sync_tool/application.conf

- name: Copy jar file.
  copy: src=sync-tool-0.0.1-SNAPSHOT.jar dest={{learner_user_home}}/sync_tool/

- name: Copy the failed event artifact to the learning machine
  copy: src="{{currentWs}}/{{artifact}}" dest={{learner_user_home}}/sync_tool/ 

- name: Run Sync tool with given command and parameters.
  shell: "java -Dconfig.file={{learner_user_home}}/sync_tool/application.conf -jar sync-tool-0.0.1-SNAPSHOT.jar {{command}} {{parameters}}"
  async: 3600
  poll: 10
  args:
    chdir: "{{learner_user_home}}/sync_tool/"
  register: job_status

- name: Print the job status to console
  debug:
    var: job_status
