- name: Create the directory
  file: path={{ cassandra_backup_dir }} state=directory recurse=yes
  
- name: copy the backup script 
  template: src=cassandra_backup.j2  dest={{ cassandra_backup_dir }}/cassandra_backup.py mode=0755 

- set_fact:
    cassandra_backup_gzip_file_name: "cassandra-backup-{{ lookup('pipe', 'date +%Y%m%d') }}.tar.gz"
 
- set_fact:
    cassandra_backup_gzip_file_path: "{{ cassandra_backup_dir }}/{{ cassandra_backup_gzip_file_name }}.tar.gz"

- name: run the backup script
  shell: python cassandra_backup.py {{ cassandra_backup_gzip_file_name }} -d {{ data_dir }}
  args:
    chdir: "{{ cassandra_backup_dir }}"
  async: 3600
  poll: 10
  
- name: Check doc_root path
  shell: ls -all {{ cassandra_backup_dir }}
  register: doc_data

- name: print doc_root to console
  debug:
    var: doc_data    
    
- name: upload file to azure storage using azcopy
  include_role:
    name: azure-cloud-storage
    tasks_from: upload-using-azcopy.yml
  vars:
    blob_container_name: "{{ cassandra_backup_storage }}"
    container_public_access: "off"
    blob_container_folder_path: ""
    local_file_or_folder_path: "{{ cassandra_backup_gzip_file_path }}"
    storage_account_name: "{{ azure_management_storage_account_name }}"
    storage_account_sas_token: "{{ azure_management_storage_account_sas }}"
  when: cloud_service_provider == "azure"

- name: clean up backup dir after upload
  file: path={{ cassandra_backup_dir }} state=absent
