- name: Make sure cassandra is up and listening
  wait_for:
    port: 9042
    timeout: 180
    sleep: 10

- name: Copy DB script
  become: yes
  template:
    src: "{{item}}.j2"
    dest: "/tmp/lp-{{item}}"
    mode: 0755
  with_items:
    - "data.cql"
    - "dialcode.cql"
  delegate_to: "{{ groups['cassandra'][0] }}"
  run_once: true

  
- name: run cql 
  become: yes
  shell: 'cqlsh -f /tmp/lp-{{item}}'
  with_items:
    - "data.cql"
    - "dialcode.cql"
  delegate_to: "{{ groups['cassandra'][0] }}"
  run_once: true
