flink_namespace: "flink-kp-{{ instance }}"
imagepullsecrets: sunbird-registry-secret

### Job manager related vars
jobmanager_rpc_port: 6123
jobmanager_blob_port: 6124
jobmanager_query_port: 6125
jobmanager_ui_port: 8081
jobmanager_prom_port: 9250
jobmanager_heap_memory: 1024
jobmanager_ui_rest_port: 80
jobmanager_ui_tcp_port: 8081
jobmanager_ui_service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

### taskmanager related vars
healthcheck: true
taskmanager_liveness:
  livenessProbe:
    tcpSocket:
      port: 6122
    initialDelaySeconds: 30
    periodSeconds: 60

taskmanager_prom_port: 9251
taskmanager_rpc_port: 6122
taskmanager_heap_memory: 1024

### base-config related vars
postgres_max_connections: 2
azure_account: "{{ sunbird_public_storage_account_name }}"
azure_secret: "{{ sunbird_public_storage_account_key }}"
flink_container_name: flink-check-points-store
checkpoint_interval: 60000
checkpoint_pause_between_seconds: 5000
checkpoint_compression_enabled: true
restart_attempts: 3
restart_delay: 30000 # in milli-seconds
producer_max_request_size: 1572864
dp_redis_host: "{{ groups['dp-redis'][0] }}"
kp_redis_host: "{{ groups['redisall'][0] }}"

### Activity Aggregate job related vars
activity_agg_consumer_parallelism: 1
activity_agg_parallelism: 1
middleware_consumption_table: "user_content_consumption"
middleware_user_activity_agg_table: "user_activity_agg"
activity_agg_checkpointing_interval: 300000
activity_agg_checkpointing_pause_interval: 90000
activity_agg_batch_interval: 60
activity_agg_batch_read_size: 1000
activity_agg_batch_write_size: 10

### Relation Cache Updater Job related Vars
extractor_consumer_parallelism: 1
relation_cache_updater_consumer_parallelism: 1
relation_cache_updater_parallelism: 1
middleware_content_hierarchy_table: "content_hierarchy"

### Post Publish Processor Job related Vars
post_publish_processor_consumer_parallesim: 1
post_publish_processor_parallelism: 1
post_publish_event_router_parallelism: 1

### Certificate Pre Processor Job related Vars
certificate_pre_processor_consumer_parallesim: 1
certificate_pre_processor_parallelism: 1
middleware_course_batch_table: "course_batch"
middleware_user_enrolments_table: "user_enrolments"
middleware_assessment_aggregator_table: "assessment_aggregator"

### taskmanager related vars
healthcheck: true
taskmanager_liveness:
  livenessProbe:
    tcpSocket:
      port: 6122
    initialDelaySeconds: 30
    periodSeconds: 60

taskmanager_prom_port: 9251
taskmanager_rpc_port: 6122
taskmanager_heap_memory: 1024
producer_max_request_size: 1572864

### to be removed
job_classname: ""

### class name vars
flink_job_names:
  activity-aggregate-updater:
    job_class_name: 'org.sunbird.job.task.ActivityAggregateUpdaterStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  relation-cache-updater:
    job_class_name: 'org.sunbird.job.task.RelationCacheUpdaterStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  post-publish-processor:
    job_class_name: 'org.sunbird.job.task.PostPublishProcessorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  certificate-pre-processor:
    job_class_name: 'org.sunbird.job.task.CertificatePreProcessorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3

### Global vars
middleware_course_keyspace: "sunbird_courses"
middleware_hierarchy_keyspace: "{{ instance }}_hierarchy_store"
neo4j_route_path: "bolt://{{ groups['learning-neo4j-node1'][0] }}:7687"
kp_search_service_base_url: "http://{{private_ingressgateway_ip}}/search"
lms_service_base_url: "http://{{private_ingressgateway_ip}}/lms"
content_service_base_url: "http://{{private_ingressgateway_ip}}/content"
cert_service_base_url: "http://{{private_ingressgateway_ip}}/certs"
learner_service_base_url: "http://{{private_ingressgateway_ip}}/learner"
