imagepullsecrets: sunbird-registry-secret

### Job manager related vars
jobmanager_rpc_port: 6123
jobmanager_blob_port: 6124
jobmanager_query_port: 6125
jobmanager_ui_port: 8081
jobmanager_prom_port: 9250
jobmanager_heap_memory: 1024
jobmanager_ui_rest_port: 80
jobmanager_ui_tcp_port: 8081
jobmanager_ui_service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"

### taskmanager related vars
healthcheck: true
taskmanager_liveness:
  livenessProbe:
    tcpSocket:
      port: 6122
    initialDelaySeconds: 30
    periodSeconds: 60

taskmanager_prom_port: 9251
taskmanager_rpc_port: 6122
taskmanager_heap_memory: 1024

### base-config related vars
postgres_max_connections: 2
flink_container_name: flink-check-points-store
checkpoint_interval: 60000
checkpoint_pause_between_seconds: 5000
checkpoint_compression_enabled: true
restart_attempts: 3
restart_delay: 30000 # in milli-seconds
producer_max_request_size: 1572864

### Activity Aggregate job related vars
activity_agg_consumer_parallelism: 1
activity_agg_dedup_parallelism: 1
activity_agg_parallelism: 1
enrolment_complete_parallelism: 1
middleware_consumption_table: "user_content_consumption"
middleware_user_activity_agg_table: "user_activity_agg"
activity_agg_checkpointing_interval: 300000
activity_agg_checkpointing_pause_interval: 90000
activity_agg_batch_interval: 60
activity_agg_batch_read_size: 2
activity_agg_batch_write_size: 10
activity_agg_window_shards: 1000
activity_agg_dedup_index: 13
activity_agg_dedup_expiry: 604800
activity_module_aggs_enabled: true
activity_input_dedup_enabled: true
activity_agg_enrolment_filter_processe_enabled: true
activity_agg_collection_status_cache_expiry_time: 3600


### Relation Cache Updater Job related Vars
extractor_consumer_parallelism: 1
relation_cache_updater_consumer_parallelism: 1
relation_cache_updater_parallelism: 1
middleware_content_hierarchy_table: "content_hierarchy"

### Post Publish Processor Job related Vars
post_publish_processor_consumer_parallelism: 1
post_publish_event_router_parallelism: 1
post_publish_shallow_copy_parallelism: 1
post_publish_link_dialcode_parallelism: 1
post_publish_batch_create_parallelism: 1

###  Certificate Job related Vars
certificate_generator_consumer_parallelism: 1
certificate_generator_parallelism: 1

### Certificate Pre & Post Processor Job related Vars
middleware_course_batch_table: "course_batch"
middleware_user_enrolments_table: "user_enrolments"
middleware_assessment_aggregator_table: "assessment_aggregator"

certificate_pre_processor_consumer_parallelism: 1
certificate_pre_processor_parallelism: 1

post_certificate_processor_consumer_parallelism: 1
post_certificate_processor_parallelism: 1


### Video stream generator related vars
### IMPORTANT: The media-service configuration values should be updated in respective environment.
azure_tenant: "{{ media_service_azure_tenant | default('') }}"
azure_subscription_id: "{{ media_service_azure_subscription_id | default('') }}"
azure_account_name: "{{ media_service_azure_account_name | default('') }}"
azure_resource_group_name: "{{ media_service_azure_resource_group_name | default('') }}"
azure_token_client_key: "{{ media_service_azure_token_client_key | default('') }}"
azure_token_client_secret: "{{ media_service_azure_token_client_secret | default('') }}"
dp_cassandra_connection_ip: "{{ groups['dp-cassandra'][0] }}"
vide_stream_generator_consumer_parallelism: 1
vide_stream_generator_parallelism: 1
vide_stream_generator_timer_duration: 10
vide_stream_generator_max_retries: 10

### Enrolment Reconciliation
enrolment_reconciliation_consumer_parallelism: 1
enrolment_reconciliation_parallelism: 1
enrolment_reconciliation_batch_write_size: 10
enrolment_reconciliation_filter_processe_enabled: true
enrolment_reconciliation_collection_status_cache_expiry_time: 3600


### to be removed
job_classname: ""

### class name vars
flink_job_names:
  activity-aggregate-updater:
    job_class_name: 'org.sunbird.job.task.ActivityAggregateUpdaterStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  relation-cache-updater:
    job_class_name: 'org.sunbird.job.task.RelationCacheUpdaterStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  post-publish-processor:
    job_class_name: 'org.sunbird.job.task.PostPublishProcessorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  questionset-publish:
    job_class_name: 'org.sunbird.job.task.QuestionSetPublishStreamTask'
    replica: 1
    jobmanager_memory: 2048m
    taskmanager_memory: 2048m
    taskslots: 1
    cpu_requests: 0.3
  video-stream-generator:
    job_class_name: 'org.sunbird.job.task.VideoStreamGeneratorStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  search-indexer:
    job_class_name: 'org.sunbird.job.task.SearchIndexerStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  enrolment-reconciliation:
    job_class_name: 'org.sunbird.job.task.EnrolmentReconciliationStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  asset-enrichment:
    job_class_name: 'org.sunbird.job.task.AssetEnrichmentStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3
  audit-history-indexer:
    job_class_name: 'org.sunbird.job.task.AuditHistoryIndexerStreamTask'
    replica: 1
    jobmanager_memory: 1024m
    taskmanager_memory: 1024m
    taskslots: 1
    cpu_requests: 0.3

### Global vars
middleware_course_keyspace: "sunbird_courses"
cloud_store: azure


### Search Indexer Related Vars
search_indexer_consumer_parallelism: 1
transaction_event_router_parallelism: 1
composite_search_indexer_parallelism: 1
dialcode_external_indexer_parallelism: 1
dialcode_metric_indexer_parallelism: 1
schema_definition_cache_expiry_in_sec: 14400

### Asset Enrichment Related Vars
asset_enrichment_consumer_parallelism: 1
asset_enrichment_router_parallelism: 1
image_enrichment_parallelism: 1
video_enrichment_parallelism: 1

### Audit history indexer Related Vars
audit_history_indexer_consumer_parallelism: 1
audit_history_indexer_parallelism: 1