- name: checking the list of installed services
  service_facts:

- name: Stop the monit
  service: name=monit state=stopped
  become: yes
  when: ansible_facts.services.monit is defined

- name: permissions
  become: yes
  #become_user: "{{learner_user}}"
  file: path={{ logstash_home }} mode=775 owner={{ learner_user }} group={{ learner_user }} recurse=yes

- name: Copy logstash configuration files for platform
  become: yes
  become_user: "{{learner_user}}"
  template: src={{item}}.j2  dest={{ logstash_home }}/{{item}}.conf
  with_items: "{{ platform.logstash_config }}"
 
- name: Stop logstash processes related to platform
  become: yes
  systemd: name=logstash state=stopped
  ignore_errors: yes
 
- name: create folder for logs
  become: yes
  become_user: "{{learner_user}}"
  file: path={{logstash_home}}/logs state=directory mode=0755
 
#- name: remove sincedb file
#  become: yes
#  become_user: "{{learner_user}}"
#  file: path={{logstash_home}}/{{ item }} state=absent
#  with_items:
#    - '.sincedb_config_telemetry_event_mw'
#    - '.sincedb_language_telemetry_event_mw'
#    - '.sincedb_learning_service_mw'
#    - '.sincedb_learning_telemetry_event_mw'
#    - '.sincedb_search_telemetry_event_mw'
 
- name: Start logstash processes related to platform
  become: yes
  systemd: name=logstash state=started 

- name: Start the monit
  service: name=monit state=started
  become: yes
  when: ansible_facts.services.monit is defined