# helm variables for the alertrules
prometheus_rule_selector_app: prometheus-operator
prometheus_rule_selector_release: prometheus-operator
fullnameOverride: sunbird-monitoring
namespace: monitoring

# Node Exporter vars
node_cpu_usage_percentage_threshold_Warning: 75
node_cpu_usage_percentage_threshold_Critical: 85
node_cpu_usage_percentage_threshold_Fatal: 95
node_memory_usage_percentage_threshold_Critical: 85
node_memory_usage_percentage_threshold_Warning: 75
node_memory_usage_percentage_threshold_Fatal: 95
node_load_avg_threshold_Critical: 95
node_load_avg_threshold_Warning: 85
node_load_avg_threshold_Fatal: 120
node_disk_usage_percentage_threshold_Warning: 75
node_disk_usage_percentage_threshold_Critical: 85
node_disk_usage_percentage_threshold_Fatal: 95
