---
# Set to "false" if you don't want to manage the package repositories from this
# role. Usefull if are behind a proxy or have a custom mirror.
es_manage_repos: true

# Elasticsearch release and version to install
es_release: "1.5"
es_minor_release: "2"
es_version: "{{ es_release }}.{{es_minor_release}}"

# Wait for elasticsearch to be listening for connections before proceeding
# (e.g. after install / restart)
es_wait_for_listen: yes

# Plugins to install, specified as:
# - name: <plugin name, including optional version string>
#   url: <optional url to download the plugin from>
#   plugin_file: <optional plugin file to check if the plugin is installed>
es_plugins: []

# Other settings can be set here

# Settings in /etc/defaults/elasticsearch, for example:
# es_default_es_user: elasticsearch
# es_default_es_group: elasticsearch
#
# See templates/elasticsearch for a full list and description of the settings
# Additional settings not on the list can also be added like this:
#
# es_default:
#   CUSTOM_VAR_ONE: 1
#   CUSTOM_VAR_TWO: two
#
# This will become:
#
# CUSTOM_VAR_ONE=1
# CUSTOM_VAR_TWO=two

# Settings in /etc/elasticsearch/elasticsearch.yml, for example:
# es_etc_cluster_name: elasticsearch
# es_etc_index_number_of_shards: 3
# See templates/elasticsearch.yml for a full list and description of the settings
#
# Additional settings not on the list can also be added like this:
#
# es_etc:
#   http.max_header_size: 16kB
#   transport.tcp.connect_timeout: 20s
#
# This will become:
#
# http.max_header_size: 16kB
# transport.tcp.connect_timeout: 20s
