---
- hosts: local
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: download artifact from azure storage
      include_role:
        name: artifacts-download-azure
        apply:
          environment:
           AZURE_STORAGE_ACCOUNT: "{{sunbird_artifact_storage_account_name}}"
           AZURE_STORAGE_SAS_TOKEN: "{{sunbird_artifact_storage_account_sas}}"
      when: cloud_service_provider == "azure"

    - name: download artifact from gcloud storage
      include_role:
        name: gcp-cloud-storage
        tasks_from: download.yml
      vars:
        gcp_bucket_name: "{{ gcloud_artifact_bucket_name }}"
        dest_folder_name: "{{ artifacts_container }}"
        dest_file_name: "{{ artifact }}"
        local_file_or_folder_path: "{{ artifact_path }}"
      when: cloud_service_provider == "gcloud"

    - name: download artifact from oci oss storage
      include_role:
        name: oci-cloud-storage
        apply:
          environment:
           OCI_CLI_AUTH: "instance_principal"        
        tasks_from: download.yml
      vars:
        oss_bucket_name: "{{ oci_artifact_oss_bucket_name }}"
        oss_object_name: "{{ artifact }}"
        local_file_or_folder_path: "{{ artifact_path }}"
      when: cloud_service_provider == "oci"