---
- hosts: cassandra
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  tasks:
    - name: copy the jar file to cassandra trigger path
      copy:
        src: "{{ item }}"
        dest: /etc/cassandra/triggers
        with_fileglob:
          - static-files/cassandra.transaction-event-handler-*.jar
  roles:
    - cassandra-triggers