---
- hosts: processing-cluster-kafka
  vars_files:
    - "{{inventory_dir}}/secrets/secrets.yml"
  pre_tasks:
    - service: name=monit state=stopped
      become: yes
      ignore_errors: true
    - name: Uncompressing and copying to system path
      unarchive:
        src: https://sunbirdpublic.blob.core.windows.net/installation/jre-8u144-linux-x64.tar.gz
        dest: /opt/
        remote_src: yes
        keep_newer: yes
      become: yes
      register: tar
    - name: Updating java jre to system path
      become: yes
      shell: update-alternatives --install /usr/bin/java java /opt/jre1.8.0_144/bin/java 9999
    - name: Registering kafka_id
      set_fact:
        kafka_id: "{% for servername in play_hosts %}{% if inventory_hostname==servername %}{{ loop.index }}{% endif %}{% endfor %}"
    - name: Print kafka_id
      debug:
        var: kafka_id
  become: yes
  roles:
    - ansible-kafka-upgrade
  become: yes
  post_tasks:
   - service: name=monit state=started
     become: yes
     ignore_errors: true