- hosts: learning1
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  become: yes
  become_user: "{{learner_user}}"
  vars_files:
    - "{{inventory_dir}}/secrets/lp_secrets.yml"
  roles:
    - lp-synctool-deploy
