apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  application.conf: |+
{{- (tpl ($.Files.Get "resources/application.conf") $) | nindent 4 }}
  content-service_application.conf: |+
{{- (tpl ($.Files.Get "templates/content-service_application.conf") $) | nindent 4 }}