learner_user: learning
learner_user_home: /home/{{learner_user}}
search_service_path: "{{learner_user_home}}/platform/service"
search_index_host: "{{ groups['composite-search-cluster']|join(':9200,')}}:9200"
search_home: "{{learner_user_home}}/platform/search/search-manager"
search_root: "{{learner_user_home}}/platform/search"
platform_api_url: "http://{{ groups['learning1'][0] }}:8080/learning-service"
instance: "{{env}}"
instance_name:
compositesearch_index_name: "compositesearch"
search_artifact_name: search-manager-1.0-SNAPSHOT
