---
zookeeper_version: 3.4.12
zookeeper_url: http://www.us.apache.org/dist/zookeeper/zookeeper-{{zookeeper_version}}/zookeeper-{{zookeeper_version}}.tar.gz
zookeeper_port: 2181
zk_jvm_opts: "-Xms128m -Xmx128m"
verify: True
apt_cache_timeout: 3600
init_limit: 5
sync_limit: 2
tick_time: 2000
zoo_id: 1
maxclinetconnection_limit: 200
data_dir: /var/lib/zookeeper
log_dir: /var/log/zookeeper
client_port: "{{ zookeeper_port }}"
# List of dict (i.e. {zookeeper_hosts:[{host:,id:},{host:,id:},...]})
# zookeeper_hosts:
#   - host: "{{inventory_hostname}}" # the machine running
#     id: 1
