###################### LP ############################

# duplicate variable as env
env_name: "{{ env }}"
cloud_storage_config_environment: "{{env}}"

ansible_vault_password: "{{lp_vault_ansible_vault_password}}"

# has to create new host group

dp_cassandra_connection: "{{ groups['dp-cassandra'][0] }}:9042"
core_cassandra_connection: "{{ groups['core-cassandra'][0] }}:9042"

dial_service_generate_url: "{{proto}}://dev.ekstep.in/api/dialcode/v3/generate"
search_service_endpoint: "{{proto}}://dev.ekstep.in/api/search/v2/search"
graph_passport_key: "{{ lp_vault_graph_passport_key }}"
secrets_path: '{{inventory_dir}}/group_vars/common.yml'
learner_user_home: "/home/{{ learner_user }}"
azure_storage_secret: "{{lp_vault_azure_storage_secret}}"
instance_name: sunbird
learner_user: learning
learner_group: learning
content_media_base_url: "{{proto}}://{{domain_name}}"      # content_media_base_url
dial_service_search_url: "{{proto}}://dev.ekstep.in/api/dialcode/v3/search"   # dial_service_search_url
learning_content_h5p_library_path: https://s3.ap-south-1.amazonaws.com/ekstep-public-dev/content/templates/h5p-library-latest.zip            # learning_content_h5p_library_path
neo4j_dir: neo4j-learning
resourcemanager: "{{ groups['yarn-master'][0] }}"
yarn_slaves: "{{ groups['yarn-slave']}}"
__yarn_host__: "{{ groups['yarn-master'][0] }}"
__yarn_port__: 8000
delayInMilliSeconds: 60000
retryTimeInMilliSeconds: 10000
retry_backoff_base_in_seconds: 10
bypass_reverse_search: true
retry_limit: 4
retry_limit_enable: true

lp_bolt_url: bolt://{{ groups['learning-neo4j-cluster'][0] }}:7687
lp_bolt_read_url: bolt://{{ groups['learning-neo4j-cluster'][0] }}:7687
lp_bolt_write_url: bolt://{{ groups['learning-neo4j-cluster'][0] }}:7687
lp_url: http://{{ groups['learningall'][0] }}:8080/learning-service
lp_tmpfile_location: /tmp
language_url: http://{{ groups['learningall'][0] }}:8080/language-service
other_bolt_url: bolt://{{ groups['learning-neo4j-cluster'][0] }}:8687
other_bolt_read_url: bolt://{{ groups['learning-neo4j-cluster'][0] }}:8687
other_bolt_write_url: bolt://{{ groups['learning-neo4j-cluster'][0] }}:8687


learnings:
  paths: ['/data', '/data/graphDB', '/data/logs', '/data/contentBundle', '/data/properties', '/home/learning/tmp', '/home/learning/platform']
  service_config: ['consumer-config.xml']

searchs:
  paths: ['/data', '/data/logs', '/data/contentBundle', '/data/properties', '/home/learning/tmp', '/home/learning/platform', '/home/learning/platform/search', '/home/learning/platform/service', '/home/learning/platform/service/logs' ]

lp_cassandra_connection: "{{groups['cassandra']|join(':9042,')}}:9042"
cloud_upload_retry_count: 3
streaming_mime_type: "video/mp4,video/webm"

zip_file: learning-graph-extension-1.0.jar
custom_procs_file: custom-procedures-1.0.jar
tr_secondary_route_events: "LOG,ERROR"
mw_shard_id: 1
google_vision_tagging: false
es_port: 9200
cassandra_host:  "{{ groups['cassandra'][0] }}"
cassandra_port: 9042
content_keyspace_table: content_data
collection_fullecar_disable: true
max_iteration_count_for_samza_job: 2
composite_search_indexer_container_count: 1
cloud_store: azure
publish_invoke_web_hook: false
compositesearch_index_name: "compositesearch"
hadoop_version: 2.7.2
redis_host: "{{ groups['redis1'][0] }}"
redis_port: 6379
kafka_brokers: "{{groups['processing-cluster-kafka']|join(':9092,')}}:9092"
zookeepers: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
google_api_key: "123"
audit_es_host: "{{ groups['composite-search-cluster']|join(':9200,')}}:9200"
search_es_host: "{{ groups['composite-search-cluster']|join(':9200,')}}:9200"

#Backup Container
cassandra_backup_azure_container_name: cassandra-backup-lp
default_channel: "01250894314817126443"


# telemetry
default_channel_id: "in.ekstep"
